webtalk_init -webtalk_dir C:/Users/Reane Sai Sulit/Documents/GitHub/MRT-7_TVM/LBYEC3G-EK1-ElAldebron_Project/LBYEC3G-EK1-ElAldebron_Project.sim/sim_1/behav/xsim/xsim.dir/TicketVendingMachine_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Nov 27 02:44:10 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3c6445e2-6b11-4dc3-8275-6ac484e91f81" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0d2b061a41a544f286ea85507b864bd2" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2096 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "40 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.05_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6852_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3263829265 -regid "212579449_0_0_167" -xml C:/Users/Reane Sai Sulit/Documents/GitHub/MRT-7_TVM/LBYEC3G-EK1-ElAldebron_Project/LBYEC3G-EK1-ElAldebron_Project.sim/sim_1/behav/xsim/xsim.dir/TicketVendingMachine_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Reane Sai Sulit/Documents/GitHub/MRT-7_TVM/LBYEC3G-EK1-ElAldebron_Project/LBYEC3G-EK1-ElAldebron_Project.sim/sim_1/behav/xsim/xsim.dir/TicketVendingMachine_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Reane Sai Sulit/Documents/GitHub/MRT-7_TVM/LBYEC3G-EK1-ElAldebron_Project/LBYEC3G-EK1-ElAldebron_Project.sim/sim_1/behav/xsim/xsim.dir/TicketVendingMachine_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
